# Generated by Django 4.2.4 on 2023-08-09 07:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='box',
            old_name='body',
            new_name='bodyEn',
        ),
        migrations.RenameField(
            model_name='box',
            old_name='title',
            new_name='titleEn',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titleEn',
        ),
        migrations.AddField(
            model_name='box',
            name='bodyJp',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='titleJp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='titleJp',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
